### ISSUE TITLE
Text vs String: Room for confusion?

### ISSUE THREAD

**Issue by etcinit** [sellerlabs/haskell-workshop#1]
It might be beneficial to stick to using `Text` or `String` throughout the examples (if its even possible), so people don't get too confused or stuck on why some functions use `Strings` and others `Text`.

On the other hand, `Text` and `String` is something we deal with on a daily basis so it might actually be good.

So perhaps an intro explaining what they are? and why not just use `String`?

**Comment by 5outh** [comment]
I think this will definitely come up as we dig into the implementation. I'll see if we can figure out how to work that discussion in nicely. Thanks for your input!

**Comment by etcinit** [comment]
I'm going to close this. Reopen if you want to keep track of it.
